### ISSUE TITLE
Remediation Not Triggering

### ISSUE THREAD

**Issue by MrPRSmith** [NicklasAhlberg/Microsoft-Endpoint-Manager#1]
Just performing some tests and noticed mixed results with the remediation not being triggered. Checking the AgentExecutor.log on a failed device showed the following ![BitLockerPIN-Error](https://user-images.githubusercontent.com/40631416/142392638-0fd40873-7aa5-4cbe-b13d-712349fdede7.png)

I edited Detect-Bitlocker-Startup-Pin.ps1 by adding the following which seems to have solved the issue for me.

$bitLockerToolProcess = Get-Process -Name Bitlocker-Startup-Pin-Tool -ErrorAction SilentlyContinue

**Comment by NicklasAhlberg** [comment]
That totally makes sense! I have updated the script now - thanks for the heads-up and for letting me know your findings!

best regards

//Nicklas

**Comment by MrPRSmith** [comment]
No worries, its a great tool - thanks for sharing it!
